# Parses Archipelago/ItemTable.cs and Archipelago/LocationTable.cs to produce the exact
# item_name_to_id / location_name_to_id data the .apworld must mirror, instead of
# hand-retyping ~760 entries (error-prone). Run from the repo root:
#
#   python tools/gen_apworld_data.py
#
# Writes apworld/bomber_crew/world_data.py (a plain data module imported by __init__.py).

import re
import os

REPO_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
ITEM_TABLE = os.path.join(REPO_ROOT, "Archipelago", "ItemTable.cs")
LOCATION_TABLE = os.path.join(REPO_ROOT, "Archipelago", "LocationTable.cs")
OUT_DIR = os.path.join(REPO_ROOT, "apworld_src", "bomber_crew")
OUT_FILE = os.path.join(OUT_DIR, "world_data.py")


def parse_items(text):
    pattern = re.compile(
        r'\{\s*(\d+),\s*new ItemDefinition\(\s*\d+,\s*"((?:[^"\\]|\\.)*)",\s*'
        r'ItemCategory\.(\w+)(?:,\s*"((?:[^"\\]|\\.)*)")?\s*\)\s*\},'
    )
    items = []
    for m in pattern.finditer(text):
        item_id, name, category, payload = m.groups()
        items.append((int(item_id), name, category, payload))
    return items


def parse_const_bases(text):
    bases = {}
    for m in re.finditer(r'private const long (\w+)\s*=\s*(\d+);', text):
        bases[m.group(1)] = int(m.group(2))
    return bases


def extract_block(text, dict_name):
    start = text.index(f"Dictionary<string, long> {dict_name} = new()")
    brace_open = text.index("{", start)
    depth = 0
    i = brace_open
    while True:
        if text[i] == "{":
            depth += 1
        elif text[i] == "}":
            depth -= 1
            if depth == 0:
                break
        i += 1
    return text[brace_open + 1:i]


def parse_mission_locations(text, bases):
    block = extract_block(text, "MissionCompletionByName")
    pattern = re.compile(r'\{\s*"([^"]+)",\s*(\w+)\s*\+\s*(\d+)\s*\}')
    locations = []
    for m in pattern.finditer(block):
        name, base_name, offset = m.groups()
        locations.append((name, bases[base_name] + int(offset)))
    return locations


def parse_shop_locations(text):
    block = extract_block(text, "ShopPurchaseByKey")
    pattern = re.compile(r'\{\s*"((?:[^"\\]|\\.)*)",\s*(\d+)\s*\}')
    return [(m.group(1), int(m.group(2))) for m in pattern.finditer(block)]


def esc(s):
    return s.replace("\\", "\\\\").replace('"', '\\"')


def main():
    item_text = open(ITEM_TABLE, encoding="utf-8").read()
    location_text = open(LOCATION_TABLE, encoding="utf-8").read()

    items = parse_items(item_text)
    bases = parse_const_bases(location_text)
    mission_locations = parse_mission_locations(location_text, bases)
    shop_locations = parse_shop_locations(location_text)

    print(f"parsed {len(items)} items")
    print(f"parsed {len(mission_locations)} mission locations")
    print(f"parsed {len(shop_locations)} shop locations")

    assert len(items) == len(set(i for i, *_ in items)), "duplicate item ids!"
    all_locations = mission_locations + shop_locations
    assert len(all_locations) == len(set(n for n, _ in all_locations)), "duplicate location names!"
    assert len(all_locations) == len(set(i for _, i in all_locations)), "duplicate location ids!"

    os.makedirs(OUT_DIR, exist_ok=True)
    with open(OUT_FILE, "w", encoding="utf-8") as f:
        f.write(
            "# GENERATED by tools/gen_apworld_data.py from Archipelago/ItemTable.cs and\n"
            "# Archipelago/LocationTable.cs. Do not hand-edit; rerun the generator instead.\n\n"
        )

        f.write("# name -> (id, category, payload)\n")
        f.write("ITEM_DATA = {\n")
        for item_id, name, category, payload in items:
            payload_repr = "None" if payload is None else f'"{esc(payload)}"'
            f.write(f'    "{esc(name)}": ({item_id}, "{category}", {payload_repr}),\n')
        f.write("}\n\n")

        f.write("MISSION_LOCATIONS = {\n")
        for name, loc_id in mission_locations:
            f.write(f'    "{esc(name)}": {loc_id},\n')
        f.write("}\n\n")

        f.write("SHOP_LOCATIONS = {\n")
        for name, loc_id in shop_locations:
            f.write(f'    "{esc(name)}": {loc_id},\n')
        f.write("}\n")

    print(f"wrote {OUT_FILE}")


if __name__ == "__main__":
    main()
